# Generated by Django 5.2.9 on 2025-12-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_job_hidden_from_owner_alter_job_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
