# Generated by Django 5.2.9 on 2025-12-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0004_historicaljob"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="model_key",
            field=models.CharField(default="runner", max_length=50),
        ),
        migrations.AddField(
            model_name="job",
            name="input_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="job",
            name="output_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="historicaljob",
            name="model_key",
            field=models.CharField(default="runner", max_length=50),
        ),
        migrations.AddField(
            model_name="historicaljob",
            name="input_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="historicaljob",
            name="output_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
