# Generated by Django 5.2.10 on 2026-02-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_model_type_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaljob',
            name='sequences',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='sequences',
            field=models.TextField(blank=True, default=''),
        ),
    ]
