# Generated by Django 5.2.10 on 2026-02-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_make_sequences_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljob',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='batch_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
