# Generated by Django 5.2.10 on 2026-02-01 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_add_batch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaljob',
            name='batch_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='batch_id',
        ),
    ]
