# Generated by Django 5.2.10 on 2026-03-06 00:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def _seconds_between(start, end):
    if not start or not end:
        return None
    return max(0, int((end - start).total_seconds()))


def backfill_phase1_runtime_fields(apps, schema_editor):
    Job = apps.get_model("jobs", "Job")
    JobAttempt = apps.get_model("jobs", "JobAttempt")

    for job in Job.objects.all().iterator():
        queued_at = job.created_at
        finished_at = job.completed_at

        if job.status in {"RUNNING", "COMPLETED", "FAILED", "CANCELLED"}:
            started_at = job.submitted_at
        else:
            started_at = None

        wait_seconds = _seconds_between(queued_at, started_at)
        run_anchor = started_at or job.submitted_at
        run_seconds = _seconds_between(run_anchor, finished_at)

        update_fields = []

        job.queued_at = queued_at
        update_fields.append("queued_at")

        if started_at is not None:
            job.started_at = started_at
            update_fields.append("started_at")

        if finished_at is not None:
            job.finished_at = finished_at
            update_fields.append("finished_at")

        if wait_seconds is not None:
            job.wait_seconds = wait_seconds
            update_fields.append("wait_seconds")

        if run_seconds is not None:
            job.run_seconds = run_seconds
            job.gpu_seconds = run_seconds
            update_fields.extend(["run_seconds", "gpu_seconds"])

        if not job.priority_tier_snapshot:
            job.priority_tier_snapshot = ""
            update_fields.append("priority_tier_snapshot")

        if not job.attempt_count:
            job.attempt_count = 1
            update_fields.append("attempt_count")

        if update_fields:
            job.save(update_fields=update_fields)

        if not JobAttempt.objects.filter(job_id=job.id).exists():
            JobAttempt.objects.create(
                job_id=job.id,
                attempt_number=1,
                status=job.status,
                scheduler_job_id=job.slurm_job_id,
                started_at=job.started_at,
                finished_at=job.finished_at,
                failure_summary=job.error_message,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0008_remove_batch_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicaljob",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="attempt_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="job",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="gpu_seconds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="priority_tier_snapshot",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="job",
            name="queued_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="job",
            name="run_seconds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="wait_seconds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaljob",
            name="attempt_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicaljob",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaljob",
            name="gpu_seconds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaljob",
            name="priority_tier_snapshot",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="historicaljob",
            name="queued_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="historicaljob",
            name="run_seconds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaljob",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaljob",
            name="wait_seconds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="JobAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempt_number", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("scheduler_job_id", models.CharField(blank=True, max_length=50)),
                ("container_id", models.CharField(blank=True, max_length=200)),
                ("gpu_index", models.PositiveIntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("exit_code", models.IntegerField(blank=True, null=True)),
                ("stdout_path", models.CharField(blank=True, max_length=500)),
                ("stderr_path", models.CharField(blank=True, max_length=500)),
                ("failure_summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "ordering": ["attempt_number"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("job", "attempt_number"),
                        name="jobs_jobattempt_unique_attempt_number",
                    )
                ],
            },
        ),
        migrations.RunPython(
            backfill_phase1_runtime_fields,
            migrations.RunPython.noop,
        ),
    ]
