# Generated by Django 5.2.10 on 2026-03-07 00:00

from django.db import migrations


def backfill_attempt_runtime_ids(apps, schema_editor):
    Job = apps.get_model("jobs", "Job")
    JobAttempt = apps.get_model("jobs", "JobAttempt")

    for job in Job.objects.exclude(slurm_job_id="").iterator():
        attempt = (
            JobAttempt.objects.filter(job_id=job.id)
            .order_by("-attempt_number")
            .first()
        )
        if attempt is None or attempt.scheduler_job_id:
            continue

        attempt.scheduler_job_id = job.slurm_job_id
        attempt.save(update_fields=["scheduler_job_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0009_phase1_runtime_domain_model"),
    ]

    operations = [
        migrations.RunPython(
            backfill_attempt_runtime_ids,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="historicaljob",
            name="slurm_job_id",
        ),
        migrations.RemoveField(
            model_name="job",
            name="slurm_job_id",
        ),
    ]
