# Generated by Django 5.2.9 on 2025-12-20 21:31

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalUserQuota",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "max_concurrent_jobs",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Maximum number of jobs that can be running simultaneously",
                    ),
                ),
                (
                    "max_queued_jobs",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Maximum number of jobs that can be pending in the queue",
                    ),
                ),
                (
                    "jobs_per_day",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Maximum number of jobs that can be submitted per day",
                    ),
                ),
                (
                    "retention_days",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Days to retain job workdirs (0 = never delete)",
                    ),
                ),
                (
                    "is_disabled",
                    models.BooleanField(
                        default=False, help_text="If true, user cannot submit new jobs"
                    ),
                ),
                (
                    "disabled_reason",
                    models.TextField(
                        blank=True, help_text="Reason for disabling the account"
                    ),
                ),
                (
                    "disabled_at",
                    models.DateTimeField(
                        blank=True, help_text="When the account was disabled", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical User Quota",
                "verbose_name_plural": "historical User Quotas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="UserQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_concurrent_jobs",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Maximum number of jobs that can be running simultaneously",
                    ),
                ),
                (
                    "max_queued_jobs",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Maximum number of jobs that can be pending in the queue",
                    ),
                ),
                (
                    "jobs_per_day",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Maximum number of jobs that can be submitted per day",
                    ),
                ),
                (
                    "retention_days",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Days to retain job workdirs (0 = never delete)",
                    ),
                ),
                (
                    "is_disabled",
                    models.BooleanField(
                        default=False, help_text="If true, user cannot submit new jobs"
                    ),
                ),
                (
                    "disabled_reason",
                    models.TextField(
                        blank=True, help_text="Reason for disabling the account"
                    ),
                ),
                (
                    "disabled_at",
                    models.DateTimeField(
                        blank=True, help_text="When the account was disabled", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quota",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Quota",
                "verbose_name_plural": "User Quotas",
            },
        ),
    ]
