# Generated by Django 5.2.10 on 2026-02-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_add_sitesettings_runnerconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrunnerconfig',
            name='cpus',
            field=models.PositiveIntegerField(default=1, help_text='CPUs per task (--cpus-per-task).'),
        ),
        migrations.AddField(
            model_name='historicalrunnerconfig',
            name='extra_env',
            field=models.JSONField(blank=True, default=dict, help_text='Additional environment variables as JSON object.'),
        ),
        migrations.AddField(
            model_name='historicalrunnerconfig',
            name='extra_mounts',
            field=models.JSONField(blank=True, default=list, help_text='Additional bind mounts as JSON array of {"source": "...", "target": "..."} objects.'),
        ),
        migrations.AddField(
            model_name='historicalrunnerconfig',
            name='gpus',
            field=models.PositiveIntegerField(default=0, help_text='Number of GPUs (--gres=gpu:N). 0 = no GPU request.'),
        ),
        migrations.AddField(
            model_name='historicalrunnerconfig',
            name='image_uri',
            field=models.CharField(blank=True, help_text="Container image override. Empty = use runner's default.", max_length=200),
        ),
        migrations.AddField(
            model_name='historicalrunnerconfig',
            name='mem_gb',
            field=models.PositiveIntegerField(default=8, help_text='Memory in GB (--mem).'),
        ),
        migrations.AddField(
            model_name='historicalrunnerconfig',
            name='partition',
            field=models.CharField(blank=True, help_text="SLURM partition (e.g., 'gpu', 'cpu'). Empty = cluster default.", max_length=50),
        ),
        migrations.AddField(
            model_name='historicalrunnerconfig',
            name='time_limit',
            field=models.CharField(blank=True, help_text="Time limit (--time, e.g., '02:00:00'). Empty = cluster default.", max_length=20),
        ),
        migrations.AddField(
            model_name='runnerconfig',
            name='cpus',
            field=models.PositiveIntegerField(default=1, help_text='CPUs per task (--cpus-per-task).'),
        ),
        migrations.AddField(
            model_name='runnerconfig',
            name='extra_env',
            field=models.JSONField(blank=True, default=dict, help_text='Additional environment variables as JSON object.'),
        ),
        migrations.AddField(
            model_name='runnerconfig',
            name='extra_mounts',
            field=models.JSONField(blank=True, default=list, help_text='Additional bind mounts as JSON array of {"source": "...", "target": "..."} objects.'),
        ),
        migrations.AddField(
            model_name='runnerconfig',
            name='gpus',
            field=models.PositiveIntegerField(default=0, help_text='Number of GPUs (--gres=gpu:N). 0 = no GPU request.'),
        ),
        migrations.AddField(
            model_name='runnerconfig',
            name='image_uri',
            field=models.CharField(blank=True, help_text="Container image override. Empty = use runner's default.", max_length=200),
        ),
        migrations.AddField(
            model_name='runnerconfig',
            name='mem_gb',
            field=models.PositiveIntegerField(default=8, help_text='Memory in GB (--mem).'),
        ),
        migrations.AddField(
            model_name='runnerconfig',
            name='partition',
            field=models.CharField(blank=True, help_text="SLURM partition (e.g., 'gpu', 'cpu'). Empty = cluster default.", max_length=50),
        ),
        migrations.AddField(
            model_name='runnerconfig',
            name='time_limit',
            field=models.CharField(blank=True, help_text="Time limit (--time, e.g., '02:00:00'). Empty = cluster default.", max_length=20),
        ),
    ]
