# Generated by Django 5.2.10 on 2026-02-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0003_add_runnerconfig_resource_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserquota',
            name='api_enabled',
            field=models.BooleanField(default=False, help_text='If true, user can access the REST API with API keys'),
        ),
        migrations.AddField(
            model_name='userquota',
            name='api_enabled',
            field=models.BooleanField(default=False, help_text='If true, user can access the REST API with API keys'),
        ),
    ]
