# Generated by Django 5.2.10 on 2026-03-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0004_historicaluserquota_api_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluserquota",
            name="jobs_per_month",
            field=models.PositiveIntegerField(
                default=300,
                help_text="Maximum number of jobs that can be submitted per calendar month",
            ),
        ),
        migrations.AddField(
            model_name="historicaluserquota",
            name="priority_tier",
            field=models.CharField(
                choices=[("standard", "Standard"), ("priority", "Priority")],
                default="standard",
                help_text="Scheduling priority tier used for queue ordering and reporting",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userquota",
            name="jobs_per_month",
            field=models.PositiveIntegerField(
                default=300,
                help_text="Maximum number of jobs that can be submitted per calendar month",
            ),
        ),
        migrations.AddField(
            model_name="userquota",
            name="priority_tier",
            field=models.CharField(
                choices=[("standard", "Standard"), ("priority", "Priority")],
                default="standard",
                help_text="Scheduling priority tier used for queue ordering and reporting",
                max_length=20,
            ),
        ),
    ]
