# Generated by Django 5.2.10 on 2026-03-07 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("console", "0005_phase1_userquota_tiers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalrunnerconfig",
            name="cpus",
        ),
        migrations.RemoveField(
            model_name="historicalrunnerconfig",
            name="extra_env",
        ),
        migrations.RemoveField(
            model_name="historicalrunnerconfig",
            name="extra_mounts",
        ),
        migrations.RemoveField(
            model_name="historicalrunnerconfig",
            name="gpus",
        ),
        migrations.RemoveField(
            model_name="historicalrunnerconfig",
            name="mem_gb",
        ),
        migrations.RemoveField(
            model_name="historicalrunnerconfig",
            name="partition",
        ),
        migrations.RemoveField(
            model_name="historicalrunnerconfig",
            name="time_limit",
        ),
        migrations.RemoveField(
            model_name="runnerconfig",
            name="cpus",
        ),
        migrations.RemoveField(
            model_name="runnerconfig",
            name="extra_env",
        ),
        migrations.RemoveField(
            model_name="runnerconfig",
            name="extra_mounts",
        ),
        migrations.RemoveField(
            model_name="runnerconfig",
            name="gpus",
        ),
        migrations.RemoveField(
            model_name="runnerconfig",
            name="mem_gb",
        ),
        migrations.RemoveField(
            model_name="runnerconfig",
            name="partition",
        ),
        migrations.RemoveField(
            model_name="runnerconfig",
            name="time_limit",
        ),
    ]
