from __future__ import annotations

from pathlib import Path

from django.conf import settings

from runners import (
    Runner,
    docker_resource_flags,
    optional_cuda_visible_devices_env_setup,
    register,
)


@register
class BindCraftRunner(Runner):
    key = "bindcraft"
    name = "BindCraft"

    def build_script(self, job, config=None) -> str:
        workdir = Path(job.workdir)
        outdir = workdir / "output"

        image = (
            config.image_uri
            if config and config.image_uri
            else settings.BINDCRAFT_IMAGE
        )

        params = job.params or {}

        # Settings file (always generated by prepare_workdir)
        settings_flag = "--settings /work/input/target_settings.json"

        # Filter and advanced: use custom uploads if present, else container defaults
        filters_flag = (
            "--filters /work/input/filters.json"
            if params.get("has_custom_filters")
            else ""
        )
        advanced_flag = (
            "--advanced /work/input/advanced.json"
            if params.get("has_custom_advanced")
            else ""
        )

        flags = [f for f in [settings_flag, filters_flag, advanced_flag] if f]
        flag_str = " \\\n    ".join(flags)

        docker_args = [
            "docker run --rm --gpus all",
            *docker_resource_flags(
                shm_size=settings.BINDCRAFT_DOCKER_SHM_SIZE,
                ipc_mode=settings.BINDCRAFT_DOCKER_IPC_MODE,
            ),
            "-e NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-all}",
            "${cuda_visible_devices_flag}",
            f"-v {workdir}:/work",
        ]
        docker_args.append(image)
        docker_args.append(
            f"python -u /app/bindcraft/bindcraft.py \\\n    {flag_str}"
        )
        docker_cmd = " \\\n  ".join(docker_args)

        return f"""#!/bin/bash
set -euo pipefail
umask 000

mkdir -p {outdir}

echo "=== GPU diagnostic ==="
nvidia-smi || echo "WARNING: nvidia-smi not available on this node"
echo "======================"

{optional_cuda_visible_devices_env_setup()}

{docker_cmd}

# Ensure output stays writable for follow-up inspection and downloads.
chmod -R a+rwX {outdir} 2>/dev/null || true
"""
