from __future__ import annotations

from pathlib import Path

from django.conf import settings

from runners import Runner, register


@register
class BindCraftRunner(Runner):
    key = "bindcraft"
    name = "BindCraft"

    def build_script(self, job, config=None) -> str:
        workdir = Path(job.host_workdir)
        outdir = workdir / "output"

        image = (
            config.image_uri
            if config and config.image_uri
            else settings.BINDCRAFT_IMAGE
        )

        slurm_directives = config.get_slurm_directives() if config else ""

        params = job.params or {}

        # Settings file (always generated by prepare_workdir)
        settings_flag = "--settings /work/input/target_settings.json"

        # Filter and advanced: use custom uploads if present, else container defaults
        filters_flag = (
            "--filters /work/input/filters.json"
            if params.get("has_custom_filters")
            else ""
        )
        advanced_flag = (
            "--advanced /work/input/advanced.json"
            if params.get("has_custom_advanced")
            else ""
        )

        flags = [f for f in [settings_flag, filters_flag, advanced_flag] if f]
        flag_str = " \\\n    ".join(flags)

        docker_args = [
            "docker run --rm --gpus all",
            f"-v {workdir}:/work",
        ]
        if config:
            for k, v in (config.extra_env or {}).items():
                docker_args.append(f"-e {k}={v}")
            for mount in config.extra_mounts or []:
                docker_args.append(f"-v {mount['source']}:{mount['target']}")
        docker_args.append(image)
        docker_args.append(
            f"python -u /app/bindcraft/bindcraft.py \\\n    {flag_str}"
        )
        docker_cmd = " \\\n  ".join(docker_args)

        return f"""#!/bin/bash
#SBATCH --job-name=bindcraft-{job.id}
#SBATCH --output={outdir}/slurm-%j.out
#SBATCH --error={outdir}/slurm-%j.err
{slurm_directives}

set -euo pipefail

mkdir -p {outdir}

{docker_cmd}

# Ensure output is readable by the webapp
chmod -R a+rX {outdir} 2>/dev/null || true
"""
